"""
Unified Tier 1 + Tier 2 reporting, shared by tests/mission/ and tests/command/.

One report is identified by (protocol, cmd_name) — protocol is "mission" or
"command", cmd_name is the MAV_CMD's bare name (e.g. "NAV_TAKEOFF"), matching
the existing SPEC.name / _CMD_NAME convention both tiers already use.
Whichever tier(s) actually ran in this pytest session are the only ones that
appear: run only test_protocol.py and the report is Tier-1-only; run both in
one invocation (e.g. `pytest tests/mission/condition_gate/`) and the report
combines both tables. There is no more per-tier logs/ file — this replaces
both tests/mission/conftest.py's and tests/command/conftest.py's own
`_write_tier1_log`, and tests/flight_helpers.py's `_write_tier2_module_log`.

Two files per report, sharing one filename prefix, written to reports/
(gitignored — regenerated by every run, not durable data worth committing):
  reports/<protocol>_<cmd_name>_<autopilot>_<vehicle>_<version>_<timestamp>.log
  reports/<protocol>_<cmd_name>_<autopilot>_<vehicle>_<version>_<timestamp>.json
Both are rewritten unconditionally after every test that touches this report
(not just once at session end), sharing one cached timestamp per
(protocol, cmd_name) key so the filename doesn't change mid-run — a run that
hangs or is force-killed still leaves whatever ran so far on disk.

The mavlink-compat-data JSON schema (github.com/hamishwillee/
mavlink-compat-data, PR #9) is rendered in exactly one place (render_json_doc
below) so a future schema change is a one-function edit, not a per-test-file
hunt — this is the "framework approach used by all tests" the schema export
was redesigned around on 2026-09-16.

Fact sources, by tier:
- Tier 1's shared base classes (Tier1MissionTestBase / Tier1CommandTestBase)
  call record_compat_fact()/record_command_fact() AUTOMATICALLY from their
  own generic per-param tests (sentinel-accepted, non-sentinel-rejected,
  baseline-supported) — no per-command code needed for these mechanical
  facts, since the base class already knows every param's identity from
  SPEC.params.
- Tier 2 tests call the same record_compat_fact()/record_command_fact() API
  explicitly, from whichever specific test is the definitive "is it
  honoured" check for a param — this part inherently needs a human judgement
  call about which test that is, so it stays an explicit call, same as
  before (see record_tier2_param_verdict's own docstring for the reasoning).
"""

from __future__ import annotations

import json
import logging
import re
import time
from pathlib import Path

import pytest

log = logging.getLogger(__name__)

Key = tuple[str, str]  # (protocol, cmd_name)

_UNSET = object()  # distinct from a real None ("not independently tested")

_TIER1_RESULTS: dict[Key, list[tuple[str, str, str, object]]] = {}
_TIER1_DETAILS: dict[Key, list[str]] = {}
_TIER2_RESULTS: dict[Key, list[tuple[str, str, str]]] = {}
_PARAM_VERDICTS: dict[Key, list[tuple[str, str]]] = {}
_COMPAT_PARAMS: dict[Key, dict[str, dict]] = {}
_COMPAT_COMMAND: dict[Key, dict] = {}
_ALL_PARAM_KEYS: dict[Key, list[str]] = {}
_CMD_ID: dict[Key, int] = {}
_TIMESTAMP: dict[Key, str] = {}


def declare_command(protocol: str, cmd_name: str, cmd_id: int) -> None:
    """Register a command's numeric id. Idempotent — first caller wins."""
    _CMD_ID.setdefault((protocol, cmd_name), cmd_id)


def declare_params(protocol: str, cmd_name: str, param_keys: list[str]) -> None:
    """
    Register the command's full canonical param-slot key list (mavlink-compat-data
    "<slot>_<Label>" form, e.g. "1_Pitch") once. Idempotent — first caller wins
    (Tier 1, if it runs in this session; a Tier-2-only run falls back to
    whatever the Tier 2 module itself declares). Every key in this list always
    appears in the rendered JSON, "supported": null for any that never got a
    fact recorded this run — distinct from a param this command doesn't cover
    at all (silently absent), which would be indistinguishable from "we forgot
    to test it".
    """
    _ALL_PARAM_KEYS.setdefault((protocol, cmd_name), param_keys)


def has_tier1_results(protocol: str, cmd_name: str) -> bool:
    return bool(_TIER1_RESULTS.get((protocol, cmd_name)))


def has_tier2_results(protocol: str, cmd_name: str) -> bool:
    return bool(_TIER2_RESULTS.get((protocol, cmd_name)))


def record_tier1_result(protocol: str, cmd_name: str, test_name: str, outcome: str, description: str, result) -> None:
    _TIER1_RESULTS.setdefault((protocol, cmd_name), []).append((test_name, outcome, description, result))


def record_tier1_detail(protocol: str, cmd_name: str, text: str) -> None:
    """Attach a supplementary multi-line block to the Tier 1 section of the report."""
    _TIER1_DETAILS.setdefault((protocol, cmd_name), []).append(text)


def record_tier2_result(protocol: str, cmd_name: str, test_name: str, outcome: str, detail: str) -> None:
    _TIER2_RESULTS.setdefault((protocol, cmd_name), []).append((test_name, outcome, detail))


def record_param_verdict(protocol: str, cmd_name: str, label: str, verdict: str) -> None:
    """
    Tag a definitive "is `label` supported" answer for the Compatibility
    summary appended after the results table(s) — e.g. "param1 (Pitch): NOT
    SUPPORTED". Call once, from whichever single test is the definitive
    check for that param/command, not from every test that happens to touch
    it. `verdict` is a short human string ("SUPPORTED", "NOT SUPPORTED",
    "NOT TESTABLE (<why>)", etc).
    """
    _PARAM_VERDICTS.setdefault((protocol, cmd_name), []).append((label, verdict))


def record_compat_fact(
    protocol: str,
    cmd_name: str,
    param_key: str,
    *,
    supported=_UNSET,  # True | False | None | "not-applicable"
    accept_nan_or_int32max: bool | None = None,
    nacks_on_non_sentinel_value: bool | None = None,
    notes: str | list[str] | None = None,
) -> None:
    """
    Merge one param's compatibility fact, mavlink-compat-data schema shape.
    Merges into whatever's already recorded for this param_key — different
    tests/tiers typically establish different facets of the same param (Tier
    1's generic sentinel probe finds `accept_nan_or_int32max`, a Tier 2
    execution test finds `supported`), and each call should accumulate, not
    clobber. Only pass the field(s) *this* call actually has evidence for.

    `param_key`: mavlink-compat-data's "<index>_<name>" form, e.g. "1_Pitch".
    `supported`: `True` (confirmed working — rendered as the
    `{"added_version": true}` object form), `False` (confirmed not working),
    `None` (not independently tested this run), or `"not-applicable"` (a
    reserved/"Empty" param slot).
    `accept_nan_or_int32max`: does this param's sentinel value get accepted.
    `nacks_on_non_sentinel_value`: does the stack correctly reject a real,
    non-sentinel value — only meaningful (and only rendered) when `supported`
    is not `True`.
    `notes`: extremely terse per mavlink-compat-data's own convention — a
    fragment, ~10 words, no period, describing observable behaviour only.
    """
    facts = _COMPAT_PARAMS.setdefault((protocol, cmd_name), {}).setdefault(param_key, {})
    if supported is not _UNSET:
        facts["supported"] = supported
    if accept_nan_or_int32max is not None:
        facts["accept_nan_or_int32max"] = accept_nan_or_int32max
    if nacks_on_non_sentinel_value is not None:
        facts["nacks_on_non_sentinel_value"] = nacks_on_non_sentinel_value
    if notes is not None:
        _merge_notes(facts, notes)


def record_command_fact(
    protocol: str,
    cmd_name: str,
    *,
    supported=_UNSET,  # True | False | None
    basis: str = "testing",
    notes: str | list[str] | None = None,
) -> None:
    """
    Merge the command-level (frame-wide) `supported`/`notes` fact — root
    CLAUDE.md rule 1: "the vehicle takes off" is the one thing a takeoff
    command's XML actually requires; this is that fact, not a per-param one.
    Same merge semantics as record_compat_fact().

    `basis` defaults to `"testing"` (this tool's own output — a real dynamic
    SITL observation) and should never be `"verified"`: per mavlink-compat-
    data's own schema, `"verified"` is reserved for a human project
    maintainer's manual sign-off, not anything an automated harness can
    claim about its own results.
    """
    facts = _COMPAT_COMMAND.setdefault((protocol, cmd_name), {})
    if supported is not _UNSET:
        facts["supported"] = supported
    facts["basis"] = basis
    if notes is not None:
        _merge_notes(facts, notes)


def _merge_notes(facts: dict, notes) -> None:
    existing = facts.get("notes")
    if existing is None:
        facts["notes"] = notes
        return
    existing_list = existing if isinstance(existing, list) else [existing]
    new_list = notes if isinstance(notes, list) else [notes]
    for n in new_list:
        if n not in existing_list:
            existing_list.append(n)
    facts["notes"] = existing_list[0] if len(existing_list) == 1 else existing_list


# ---------------------------------------------------------------------------
# mavlink-compat-data JSON rendering — the ONE place the schema shape lives.
# ---------------------------------------------------------------------------

# --vehicle-type (as this harness's CLI already uses it) -> mavlink-compat-data
# vocab.json frame name. "fixed_wing" is stack-dependent (px4: fixedwing,
# ardupilot: plane) so it's resolved separately in _compat_json_frame().
_COMPAT_FRAME_MAP = {
    "quadcopter": "multicopter",
    "vtol": "vtol",
    "quadplane": "standard_quadplane",
    "copter": "copter",
    "rover": "rover",
}


def _compat_json_frame(autopilot: str, vehicle_type: str) -> str | None:
    """Map this harness's (--autopilot, --vehicle-type) to a mavlink-compat-data vocab.json frame name."""
    if vehicle_type == "fixed_wing":
        return "fixedwing" if autopilot == "px4" else "plane"
    return _COMPAT_FRAME_MAP.get(vehicle_type)


def _is_dev_build(firmware_version: str) -> bool:
    return bool(re.search(r"(?i)-dev\b|-beta\b|-rc\d|\bmain\b", firmware_version))


def _dev_build_comment(firmware_version: str) -> str:
    return (
        f"# NOTE: {firmware_version} is a dev/pre-release build — per mavlink-compat-data's\n"
        f"# own convention, retest against a tagged release before treating this as durable\n"
        f"# data (this is why the earliest/last_checked_version field is omitted below —\n"
        f"# a git commit isn't a stable, re-comparable version identity).\n"
    )


def _render_param(fact: dict) -> dict:
    supported = fact.get("supported")  # a param may accumulate only sentinel facts, never a supported call
    out: dict = {}
    if supported is True:
        sup: dict = {"added_version": True}
        if fact.get("accept_nan_or_int32max") is not None:
            sup["accept_nan_or_int32max"] = fact["accept_nan_or_int32max"]
        out["supported"] = sup
    else:
        out["supported"] = supported  # False / None / "not-applicable"
        if fact.get("accept_nan_or_int32max") is not None:
            out["accept_nan_or_int32max"] = fact["accept_nan_or_int32max"]
        if fact.get("nacks_on_non_sentinel_value") is not None:
            out["nacks_on_non_sentinel_value"] = fact["nacks_on_non_sentinel_value"]
    if fact.get("notes"):
        out["notes"] = fact["notes"]
    return out


def render_json_doc(protocol: str, cmd_name: str, config) -> dict | None:
    """
    Build the mavlink-compat-data-shaped dict for this (protocol, cmd_name),
    or None if nothing was ever recorded this run. A frame-mapping failure
    (unrecognised --autopilot/--vehicle-type) renders as {"error": "..."}
    rather than returning None, so the .json report file is always either
    absent or valid, parseable JSON — never a comment-only non-JSON string.
    """
    key = (protocol, cmd_name)
    params = _COMPAT_PARAMS.get(key)
    command = _COMPAT_COMMAND.get(key)
    all_keys = _ALL_PARAM_KEYS.get(key)
    if all_keys:
        params = {k: (params or {}).get(k, {}) for k in all_keys}
    if not params and not command:
        return None

    info = getattr(config, "_autopilot_info", {}) or {}
    autopilot = (info.get("autopilot") or "").lower()
    vehicle_type = config.getoption("--vehicle-type") or ""
    frame = _compat_json_frame(autopilot, vehicle_type)
    if autopilot not in ("px4", "ardupilot") or frame is None:
        return {
            "error": (
                f"Could not map autopilot={autopilot!r}/vehicle_type={vehicle_type!r} to a "
                "mavlink-compat-data (stack, frame) pair (schema/vocab.json) — pass "
                "--autopilot/--vehicle-type matching that vocab, or fill this in by hand."
            )
        }

    firmware_version = info.get("firmware_version", "") or ""
    # mavlink-compat-data's own convention: never record a version fact
    # purely from a dev/pre-release snapshot — a specific git commit isn't a
    # stable, re-comparable identity. Still render the JSON, just omit the
    # version field (basis is unaffected — see below, it's always "testing"
    # regardless of dev/release).
    is_dev_build = _is_dev_build(firmware_version)
    bare_version = firmware_version.split("-")[0] if firmware_version else None

    # required by frameStatus: `supported`+`basis` must always be present.
    # Default to the schema's own "nothing established yet" pair when this
    # command never got an explicit record_command_fact() call (e.g. only
    # per-param facts were recorded) — matches upstream's own precedent for
    # an unestablished fact (`"supported": null, "basis": "unknown"`).
    cmd_supported = command.get("supported") if command is not None else None
    confirmed_supported = cmd_supported is True  # the schema's "confirmed-implemented object" case
    frame_obj: dict = {
        "supported": {"added_version": True} if confirmed_supported else cmd_supported,
        # "testing": this tool's own dynamic-SITL-observation basis, always —
        # never "verified", which the schema reserves for a human project
        # maintainer's manual sign-off, not anything we can claim ourselves.
        "basis": "testing" if command is None else command.get("basis", "testing"),
    }
    if command is not None and command.get("notes"):
        frame_obj["notes"] = command["notes"]
    if bare_version and not is_dev_build:
        # earliest_checked_version: a lower bound on "added_version: true"
        # (known supported, exact introduction version unrecorded) — only
        # meaningful in the confirmed-supported case. Everywhere else
        # (unsupported, untested, not-applicable) there's no "when was it
        # added" question to bound; last_checked_version ("still true as of
        # this version we most recently ran") is the field that applies.
        if confirmed_supported:
            frame_obj["earliest_checked_version"] = bare_version
        else:
            frame_obj["last_checked_version"] = bare_version

    if params:
        # Per schema (frameStatus.params): an ordinary (non-"<n>_Empty") param
        # may appear only when this frame's own `supported` is the confirmed-
        # implemented object form — a reserved "<n>_Empty" key is exempt
        # (it carries protocol-level sentinel facts independent of whether
        # the command itself is supported). Drop everything else when this
        # frame isn't confirmed supported.
        rendered_params = {k: v for k, v in params.items() if confirmed_supported or k.endswith("_Empty")}
        if rendered_params:
            frame_obj["params"] = {k: _render_param(v) for k, v in sorted(rendered_params.items())}

    return {autopilot: {"frames": {frame: frame_obj}}}


def render_json(protocol: str, cmd_name: str, config) -> str | None:
    doc = render_json_doc(protocol, cmd_name, config)
    return None if doc is None else json.dumps(doc, indent=2)


# ---------------------------------------------------------------------------
# Combined text report + file writing
# ---------------------------------------------------------------------------

def render_text(protocol: str, cmd_name: str, cmd_id: int, config) -> str:
    """Combined Tier 1 + Tier 2 + compatibility summary text — only the tiers that actually ran appear."""
    from tests.conftest import _format_autopilot_header

    key = (protocol, cmd_name)
    info = getattr(config, "_autopilot_info", {})
    drone_address = config.getoption("--drone-address")
    header = _format_autopilot_header(info, drone_address)

    lines: list[str] = []

    t1 = _TIER1_RESULTS.get(key)
    if t1:
        counts: dict[str, int] = {}
        lines += [
            f"Tier 1 results: MAV_CMD_{cmd_name} (cmd={cmd_id})",
            "=" * 100,
            f"{'Test':<52} {'Outcome':<12} {'Result':<20} Pass case",
            "-" * 100,
        ]
        for name, outcome, description, result in t1:
            counts[outcome] = counts.get(outcome, 0) + 1
            result_str = "-" if result is None else str(result)
            lines.append(f"{name:<52} {outcome:<12} {result_str:<20} {description}")
        lines.append("-" * 100)
        lines.append(f"Total: {len(t1)}  " + "  ".join(f"{k}={v}" for k, v in sorted(counts.items())))
        details = _TIER1_DETAILS.get(key)
        if details:
            lines += ["", "Supplementary detail", "=" * 100, *details]

    t2 = _TIER2_RESULTS.get(key)
    if t2:
        if lines:
            lines.append("")
        counts = {}
        lines += [
            f"Tier 2 results: MAV_CMD_{cmd_name} (cmd={cmd_id})",
            "=" * 100,
            f"{'Test':<46} {'Outcome':<9} Detail",
            "-" * 100,
        ]
        for test_name, outcome, detail in t2:
            counts[outcome] = counts.get(outcome, 0) + 1
            lines.append(f"{test_name:<46} {outcome:<9} {detail}")
        lines.append("-" * 100)
        lines.append(f"Total: {len(t2)}  " + "  ".join(f"{k}={v}" for k, v in sorted(counts.items())))

    verdicts = _PARAM_VERDICTS.get(key)
    if verdicts:
        lines += ["", "Compatibility summary", "=" * 100]
        width = max(len(p) for p, _ in verdicts)
        for param_label, verdict in verdicts:
            lines.append(f"{param_label:<{width}}  {verdict}")

    compat_json = render_json(protocol, cmd_name, config)
    if compat_json:
        fw = (info.get("firmware_version") or "")
        prefix = _dev_build_comment(fw) if _is_dev_build(fw) else ""
        lines += [
            "",
            "Compatibility JSON (mavlink-compat-data schema — github.com/hamishwillee/mavlink-compat-data)",
            "=" * 100,
            prefix + compat_json,
        ]

    return header + "\n\n" + "\n".join(lines) + "\n"


def _safe(s: str) -> str:
    return s.replace("/", "_").replace(" ", "_").replace("\\", "_")


def write(protocol: str, cmd_name: str, cmd_id: int, config) -> None:
    """
    (Re)write both report files unconditionally, overwriting the same paths
    each time — called after every test that touches this report, not just
    once at session end, so a hung/killed run still leaves whatever ran so
    far on disk.

    No-op for mock/paired-mode runs (--drone-address omitted) unless
    --write-mock-reports is passed: mock isn't a real flight stack/frame, so
    its .json can never be more than {"error": "..."} (see render_json_doc)
    and its .log has no compatibility-data value — just noise in reports/.
    """
    if config.getoption("--drone-address") is None and not config.getoption("--write-mock-reports"):
        return
    declare_command(protocol, cmd_name, cmd_id)
    key = (protocol, cmd_name)
    info = getattr(config, "_autopilot_info", {})
    ap = _safe(info.get("autopilot", "unknown").lower().replace("ardupilotmega", "ardupilot"))
    vt = _safe(info.get("vehicle_type", "unknown").lower())
    ver_raw = info.get("firmware_version", "")
    ver = f"_{_safe(ver_raw)}" if ver_raw and ver_raw != "N/A" else ""
    timestamp = _TIMESTAMP.setdefault(key, time.strftime("%Y%m%d_%H%M%S"))

    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)
    safe_name = _safe(cmd_name.lower())
    base = f"{protocol}_{safe_name}_{ap}_{vt}{ver}_{timestamp}"

    text = render_text(protocol, cmd_name, cmd_id, config)
    log.info("\n%s", text)
    log_path = reports_dir / f"{base}.log"
    log_path.write_text(text)

    compat_json = render_json(protocol, cmd_name, config)
    if compat_json:
        json_path = reports_dir / f"{base}.json"
        json_path.write_text(compat_json + "\n")

    log.info("%-14s | %-44s | %s", cmd_name, "Report written", str(log_path))


# ---------------------------------------------------------------------------
# Generic per-test auto-recording for bespoke Tier 1 test files
# ---------------------------------------------------------------------------
# Tier1MissionTestBase/Tier1CommandTestBase record their own generic tests'
# results explicitly (via _check()/_record() in each conftest.py). A bespoke
# Tier 1 file — hand-rolled classes with command-specific scenario tests the
# shared base class's generic checks don't cover (e.g. do_reposition's mode-
# gating tests) — has no equivalent hook. This fixture is that hook: the
# same "read the stashed pytest report at teardown" mechanism tests/flight_
# helpers.py's `_tier2_auto_record` already uses for Tier 2, applied to
# Tier 1 instead, so every test in a bespoke file shows up in the combined
# report with zero changes to the test's own body/assertions.

def key_from_module(module) -> Key | None:
    """
    (protocol, cmd_name) for a test module — protocol ("mission"/"command")
    inferred from its package path, cmd_name from its `_CMD_NAME` constant.
    None if the module is missing `_CMD_NAME`, or lives outside both trees.
    Shared by both tiers' auto-record fixtures (this module's own
    `_tier1_auto_record` below, and tests/flight_helpers.py's Tier 2
    equivalent) so "how do we identify which report a test belongs to" is
    defined in exactly one place.
    """
    if module is None:
        return None
    name = getattr(module, "_CMD_NAME", None)
    if name is None:
        return None
    module_name = module.__name__
    if ".mission." in module_name:
        return ("mission", name)
    if ".command." in module_name:
        return ("command", name)
    return None


@pytest.fixture(autouse=True)
def _tier1_auto_record(request):
    """
    Generic per-test PASS/FAIL/SKIP/XFAIL capture for a bespoke Tier 1 test
    file that ISN'T built on Tier1MissionTestBase/Tier1CommandTestBase.
    Mirrors tests/flight_helpers.py's `_tier2_auto_record` exactly (down to
    reading the same `item._report_call`/`_report_setup` stashed by tests/
    conftest.py's `pytest_runtest_makereport` hook), just writing into the
    Tier 1 section of the combined report instead of Tier 2.

    Adopting this costs the same two module-level constants and one import
    as the Tier 2 version: declare `_CMD_NAME`/`_CMD_ID` (reuse an existing
    `_CMD`-style constant under a different name if the file already has
    one), and import `_tier1_auto_record` from `tests.report` (autouse=True
    — importing a fixture by name into a test module's namespace is what
    activates it). A module already subclassing Tier1MissionTestBase/
    Tier1CommandTestBase does not need this for that base class's own
    generic tests (they self-record) — but importing this too is harmless
    and correctly picks up any *additional* bespoke test methods/classes in
    the same file that aren't part of the base class.
    """
    yield
    node = request.node
    rep = getattr(node, "_report_call", None) or getattr(node, "_report_setup", None)
    if rep is None:
        return  # e.g. collection error before any phase ran

    if getattr(rep, "skipped", False):
        outcome = "XFAIL" if hasattr(rep, "wasxfail") else "SKIP"
    elif getattr(rep, "passed", False):
        outcome = "XPASS" if hasattr(rep, "wasxfail") else "PASS"
    else:
        outcome = "FAIL"

    if outcome == "SKIP" and isinstance(rep.longrepr, tuple) and len(rep.longrepr) == 3:
        reason = str(rep.longrepr[2]).removeprefix("Skipped: ")
        detail = reason[:160]
    elif outcome in ("FAIL", "XFAIL") and rep.longrepr:
        detail = str(rep.longrepr).strip().splitlines()[-1][:160]
    else:
        doc = (node.function.__doc__ or "").strip()
        detail = doc.splitlines()[0].strip() if doc else ""

    key = key_from_module(node.module)
    if key is None:
        return
    protocol, cmd_name = key
    record_tier1_result(protocol, cmd_name, node.name, outcome, detail, None)
    cmd_id = getattr(node.module, "_CMD_ID", None)
    if cmd_id is not None:
        write(protocol, cmd_name, cmd_id, request.config)
